# Generated by Django 5.0.6 on 2024-06-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('unit', models.FileField(upload_to='')),
                ('building_images', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('kitchen', models.BooleanField(default=False)),
                ('bathroom', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('solar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.images', verbose_name='images')),
                ('units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.units', verbose_name='units')),
            ],
        ),
    ]
