# Generated by Django 5.0.6 on 2024-07-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=500, null=True)),
                ('booked_count', models.IntegerField(blank=True, default=0)),
                ('subscribers_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Commercial', 'Commercial'), ('House', 'House'), ('Shop', 'Shop'), ('Cabin', 'Cabin'), ('Warehouse', 'Warehouse'), ('Tent', 'Tent')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('file', models.FileField(upload_to='')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='app1.category'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('kitchen', models.BooleanField(default=False)),
                ('bathroom', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('solar', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('booked_count', models.IntegerField(blank=True, default=0)),
                ('unit_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.building')),
            ],
        ),
        migrations.CreateModel(
            name='UnitImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('file', models.FileField(upload_to='')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.unit')),
            ],
        ),
    ]
