# Generated by Django 5.0.6 on 2024-09-22 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
