# Generated by Django 5.0.6 on 2024-06-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_building_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='images',
        ),
        migrations.AddField(
            model_name='building',
            name='images',
            field=models.ManyToManyField(null=True, to='app1.images', verbose_name='images'),
        ),
    ]
