# Generated by Django 5.0.6 on 2024-08-08 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
