# Generated by Django 5.0.6 on 2024-06-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_building_images_building_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='building_images',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='images',
            name='unit',
        ),
    ]
