# Generated by Django 5.0.6 on 2024-06-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_building_images_images_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='images',
        ),
        migrations.AddField(
            model_name='building',
            name='images',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.images', verbose_name='related place'),
        ),
    ]
