# Generated by Django 5.0.6 on 2024-08-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_subscription_subscribed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="app1.property",
            ),
        ),
    ]
