# Generated by Django 5.0.6 on 2024-09-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_unit_unit_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="app1.property",
            ),
        ),
    ]
