# Generated by Django 5.0.6 on 2024-09-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_unit_unit_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="occupied",
            field=models.BooleanField(default=False),
        ),
    ]
