# Generated by Django 5.0.6 on 2024-06-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_building_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
