# Generated by Django 5.0.6 on 2024-09-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_property_occupied"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="unit",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
