# Generated by Django 5.0.6 on 2024-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_building_units_building_location_unit_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
