# Generated by Django 5.0.6 on 2024-09-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_alter_property_price_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
