# Generated by Django 5.0.6 on 2024-06-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_units_unit_unit_building_unit_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.building', verbose_name='building'),
        ),
    ]
