# Generated by Django 5.0.6 on 2024-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_alter_property_price_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
