# Generated by Django 5.0.6 on 2024-09-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_property_pinned_property_pinned_at_pinnedproperty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="pinned",
        ),
        migrations.RemoveField(
            model_name="property",
            name="pinned_at",
        ),
    ]
