# Generated by Django 5.0.6 on 2024-07-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_subscription"),
        ("bookings", "0002_booking_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.unit",
            ),
        ),
    ]
