# Generated by Django 5.0.6 on 2024-09-06 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
