# Generated by Django 5.0.6 on 2024-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_booking_type_booking_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(default="Unspecified", max_length=50),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
