# Generated by Django 5.0.6 on 2024-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_booking_type_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
